{
 "title": "City Weather Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Top Searched Cities",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "city_search_count_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "City Weather Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "city_weather_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Invalid City Searches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "invalid_city_search_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Temperature Unit (°C/°F) Count",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "temp_unit_selection_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Searched Data",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "targets": [
    { "expr": "city_temperature_value", "legendFormat": "__auto" }
   ]
  }
 ]
}